### ISSUE TITLE
只能下载公开的吗

### ISSUE THREAD

**Issue by Rrubidium** [gxr404/yuque-dl#1]
只能下载公开的吗，我有个别人共享给我的笔记，我只有阅读权限，如何用我的账户去下载呢

**Comment by gxr404** [comment]
请更新到最新版1.0.17  `npm i -g yuque-dl`
然后登录语雀后[复制token](https://github.com/gxr404/yuque-dl/blob/main/GET_TOEKN.md) 
添加-t参数即可下载别人分享的私有知识库
```bash
yuque-dl 私有知识库url -t token
```

**Comment by Rrubidium** [comment]
谢谢谢谢，非常完美的解决了我的问题
