### ISSUE TITLE
还可以用吗？

### ISSUE THREAD

**Issue by a186232641** [gxr404/yuque-dl#10]

**Comment by a186232641** [comment]
npm WARN deprecated date-format@2.1.0: 2.x is no longer supported. Please upgrade to 4.x or higher.
npm WARN deprecated streamroller@2.2.4: 2.x is no longer supported. Please upgrade to 3.x or higher.
npm WARN deprecated log4js@5.3.0: 5.x is no longer supported. Please upgrade to 6.x or higher.

changed 66 packages in 5s

18 packages are looking for funding
  run `npm fund` for details
 ~   master ± 

**Comment by a186232641** [comment]
这个问题如何解决？

**Comment by gxr404** [comment]
> npm WARN deprecated date-format@2.1.0: 2.x is no longer supported. Please upgrade to 4.x or higher. npm WARN deprecated streamroller@2.2.4: 2.x is no longer supported. Please upgrade to 3.x or higher. npm WARN deprecated log4js@5.3.0: 5.x is no longer supported. Please upgrade to 6.x or higher.
> 
> changed 66 packages in 5s
> 
> 18 packages are looking for funding run `npm fund` for details ~   master ± 

警告并不影响运行
![SCR-20240403-onao](https://github.com/gxr404/yuque-dl/assets/17134256/335b798e-8be1-41f3-8ca0-c46d5b797f7c)

**Comment by a186232641** [comment]
yuque-dl "https://www.yuque.com/yuque/thyzgp"
zsh: command not found: yuque-dl

**Comment by gxr404** [comment]
如果确定是执行了 `npm i -g yuque-dl` 报的这个错，那就应该是环境变量的问题了

**Comment by a186232641** [comment]
感谢您，是我电脑系统的问题
