### ISSUE TITLE
生成的markdown文件中出现大量多余的a标签

### ISSUE THREAD

**Issue by dzdzdzd123** [gxr404/yuque-dl#14]
样例如：
<a name="Y40dy"></a>
<a name="ns9JJ"></a>
1、多余的a标签。是和标题关联的跳转a标签，我用的typora，跳转不了，不起作用，不知道其他编辑器能不能跳（sourcecode中返回的）
2、`<!--page header-->`和`<!--page footer-->`也有特殊的用途吗？typora看不出来

![image](https://github.com/gxr404/yuque-dl/assets/37803298/8cad68ba-80d2-4536-85c7-aaf8ae623504)

**Comment by gxr404** [comment]
1. 多余的a标签是由语雀的接口返回的，没有toc也没啥用 已移除
2. header footer是由我这边加的，暂时没啥特殊的用途 已移除

请更新至`v1.0.33`，上面两点已经做了处理
不过主要还是typora 不支持 markdown内部分html的解析，
我也无法保证接口返回的一定不含有html
