### ISSUE TITLE
公开加密文档没有了verified_books或者verified_docs这个字段

### ISSUE THREAD

**Issue by Softssiter** [gxr404/yuque-dl#15]
我也想下载一个公开加密知识库，看了一下issue，发现上次有老哥也是下载那个，跟着看了一下，发现现在f12之后，已经找不到对应的字段，现在要如何才能下载公开加密知识库呢

**Comment by Softssiter** [comment]
可以了，我后面挨着试了一下，用_yuque_session这个，加对应的值是可以的
 -k="_yuque_session" -t "_yuque_session值“

**Comment by gxr404** [comment]
公开加密知识库是需要**输入密码**后才能访问的 应该输入密码后才会有verified_books，你说的是这种吗
<img width="1112" alt="SCR-20240504-qxbe" src="https://github.com/gxr404/yuque-dl/assets/17134256/7a0296a9-94d3-405e-8855-22d9fc5f52fc">

**Comment by Softssiter** [comment]
> > 可以了，我后面挨着试了一下，用_yuque_session这个，加对应的值是可以的 -k="_yuque_session" -t "_yuque_session值“
> 
> 公开加密知识库是需要**输入密码**后才能访问的 应该输入密码后才会有verified_books，你说的是这种吗 <img alt="SCR-20240504-qxbe" width="1112" src="https://private-user-images.githubusercontent.com/17134256/327944537-7a0296a9-94d3-405e-8855-22d9fc5f52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mzc1NjEsIm5iZiI6MTcxNDgzNzI2MSwicGF0aCI6Ii8xNzEzNDI1Ni8zMjc5NDQ1MzctN2EwMjk2YTktOTRkMy00MDVlLTg4NTUtMjJkOWZjNWY1MmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE1NDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTQzMDE0M2ZmOTY5MDJmY2EwYzk2OTgzYjAzYTMxOWE0YTk2Yzk0ZWNjNThjNjY2OGU2MDgyYzAxNmJhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avUTBgnM37QYQ3Utdq0fZOw-dMQi5WD9ZlGuXP-ZIog">

对，就是这种，我是输了密码了，在里面之后f12查看的，确实是没有看到verified_books这个字段，但是用_yuque这个可以下载，已经下载好了

**Comment by gxr404** [comment]
> > > 可以了，我后面挨着试了一下，用_yuque_session这个，加对应的值是可以的 -k="_yuque_session" -t "_yuque_session值“
> > 
> > 
> > 公开加密知识库是需要**输入密码**后才能访问的 应该输入密码后才会有verified_books，你说的是这种吗 <img alt="SCR-20240504-qxbe" width="1112" src="https://private-user-images.githubusercontent.com/17134256/327944537-7a0296a9-94d3-405e-8855-22d9fc5f52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mzc1NjEsIm5iZiI6MTcxNDgzNzI2MSwicGF0aCI6Ii8xNzEzNDI1Ni8zMjc5NDQ1MzctN2EwMjk2YTktOTRkMy00MDVlLTg4NTUtMjJkOWZjNWY1MmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE1NDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTQzMDE0M2ZmOTY5MDJmY2EwYzk2OTgzYjAzYTMxOWE0YTk2Yzk0ZWNjNThjNjY2OGU2MDgyYzAxNmJhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avUTBgnM37QYQ3Utdq0fZOw-dMQi5WD9ZlGuXP-ZIog">
> 
> 对，就是这种，我是输了密码了，在里面之后f12查看的，确实是没有看到verified_books这个字段，但是用_yuque这个可以下载，已经下载好了

试了下 大概是这样的 😂
 - 如果你登录了语雀账号  访问需要密码访问的知识库 输入密码后是没有 `verified_books` 用 `_yuque_session`
 - 如果你没登录语雀账号  访问需要密码访问的知识库输入密码后只有`verified_books/verified_docs`

**Comment by Softssiter** [comment]
> > > > 可以了，我后面挨着试了一下，用_yuque_session这个，加对应的值是可以的 -k="_yuque_session" -t "_yuque_session值“
> > > 
> > > 
> > > 公开加密知识库是需要**输入密码**后才能访问的 应该输入密码后才会有verified_books，你说的是这种吗 <img alt="SCR-20240504-qxbe" width="1112" src="https://private-user-images.githubusercontent.com/17134256/327944537-7a0296a9-94d3-405e-8855-22d9fc5f52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Mzc1NjEsIm5iZiI6MTcxNDgzNzI2MSwicGF0aCI6Ii8xNzEzNDI1Ni8zMjc5NDQ1MzctN2EwMjk2YTktOTRkMy00MDVlLTg4NTUtMjJkOWZjNWY1MmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDE1NDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTQzMDE0M2ZmOTY5MDJmY2EwYzk2OTgzYjAzYTMxOWE0YTk2Yzk0ZWNjNThjNjY2OGU2MDgyYzAxNmJhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avUTBgnM37QYQ3Utdq0fZOw-dMQi5WD9ZlGuXP-ZIog">
> > 
> > 
> > 对，就是这种，我是输了密码了，在里面之后f12查看的，确实是没有看到verified_books这个字段，但是用_yuque这个可以下载，已经下载好了
> 
> 试了下 大概是这样的 😂
> 
> * 如果你登录了语雀账号  访问需要密码访问的知识库 输入密码后是没有 `verified_books` 用 `_yuque_session`
> * 如果你没登录语雀账号  访问需要密码访问的知识库输入密码后只有`verified_books/verified_docs`

原来如此，感谢解答，哈哈哈哈
