### ISSUE TITLE
下载的图片都是损坏的无法打开  是我的操作问题吗

### ISSUE THREAD

**Issue by xmqygg** [gxr404/yuque-dl#16]

**Comment by gxr404** [comment]
网页上 图片正常吗

**Comment by xmqygg** [comment]
> 网页上图片正常吗

是正常的  下载下来的图片比较多 只有很少几张是正常的 我有尝试手机端和pc端多种方式
![PixPin_2024-05-07_14-44-09](https://github.com/gxr404/yuque-dl/assets/76095052/58c32208-fea1-4c43-afcf-2d7036c581fb)
![PixPin_2024-05-07_14-45-12](https://github.com/gxr404/yuque-dl/assets/76095052/9b482fda-774f-4831-8f22-a31e24febd50)

**Comment by gxr404** [comment]
方便给个语雀链接吗 或者从网页上复制图片的链接

**Comment by xmqygg** [comment]
https://www.yuque.com/api/filetransfer/images?url=http%3A%2F%2Fglorious.icu%2Fsky-take-out%2Fimage-20221106200821282.png&sign=810804669a4d7f1c82b4006d6e190d885c11cc6ed7e06926964f492439142b94
![PixPin_2024-05-07_15-04-01](https://github.com/gxr404/yuque-dl/assets/76095052/57e496ba-75d2-4458-8382-8e73772c93f0)

**Comment by xmqygg** [comment]
> 方便给个语雀链接吗 或者从网页上复制图片的链接

老哥您好，刚看了下，一个文档内图片存在两种来源：1）CDN可以正常下载； 2）对象存储下载的都是是损坏的

**Comment by gxr404** [comment]
> > 方便给个语雀链接吗 或者从网页上复制图片的链接
> 
> 老哥您好，刚看了下，一个文档内图片存在两种来源：1）CDN可以正常下载； 2）对象存储下载的都是是损坏的

尝试修复了下，更新到1.0.36， 麻烦帮忙验证下，我这边没类似的知识库🙏

**Comment by xmqygg** [comment]
![Uploading PixPin_2024-05-08_09-44-49.png…]()

**Comment by gxr404** [comment]
> 问题还是存在1.0.36 ![Clip_2024-05-08_09-47-28](https://private-user-images.githubusercontent.com/76095052/328726813-f0490309-aa34-481f-a903-b63bdfbe6372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzMzNzEsIm5iZiI6MTcxNTEzMzA3MSwicGF0aCI6Ii83NjA5NTA1Mi8zMjg3MjY4MTMtZjA0OTAzMDktYWEzNC00ODFmLWE5MDMtYjYzYmRmYmU2MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjA4ZmNmNDFiZWE3ZGFhOTVhZDM3NGQzY2EwZDU2MjViNmVmOTZjM2NmYWVhNzIzZWQ5M2FjZDI0MTc4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QVzIAqr8e3JyXSr-k7q2O_YHOjDUZaflud3cu25HaE)

终端有显示什么错误吗

**Comment by xmqygg** [comment]
> > 问题还是存在1.0.36 ![Clip_2024-05-08_09-47-28](https://private-user-images.githubusercontent.com/76095052/328726813-f0490309-aa34-481f-a903-b63bdfbe6372.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzMzNzEsIm5iZiI6MTcxNTEzMzA3MSwicGF0aCI6Ii83NjA5NTA1Mi8zMjg3MjY4MTMtZjA0OTAzMDktYWEzNC00ODFmLWE5MDMtYjYzYmRmYmU2MzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAxNTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjA4ZmNmNDFiZWE3ZGFhOTVhZDM3NGQzY2EwZDU2MjViNmVmOTZjM2NmYWVhNzIzZWQ5M2FjZDI0MTc4OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QVzIAqr8e3JyXSr-k7q2O_YHOjDUZaflud3cu25HaE)
> 
> 终端有显示什么错误吗

并没有，昨晚我有尝试增加日志输出但没成功

**Comment by gxr404** [comment]
知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗

**Comment by xmqygg** [comment]
> 知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗

**Comment by xmqygg** [comment]
> > 知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗

**Comment by xmqygg** [comment]
> > > 知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗

yuque-dl "https://www.yuque.com/cq2022/study-note/cy4yygdf7f139xkk"

**Comment by xmqygg** [comment]
> > > 知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗

上一条链接给错了，应该是https://www.yuque.com/icu0/java/rp4duq11wv6ir9y3

**Comment by gxr404** [comment]
已修复，更新至1.0.40

**Comment by gxr404** [comment]
> > > > 知识库是公开的吗 没实际的知识库 不好调试查找问题，上面的`3.搭建开发环境`的那张图 还是没有吗
> 
> 上一条链接给错了，应该是[yuque.com/icu0/java/rp4duq11wv6ir9y3](https://www.yuque.com/icu0/java/rp4duq11wv6ir9y3)

已修复，更新至1.0.40
