### ISSUE TITLE
父级文档无法下载

### ISSUE THREAD

**Issue by Greygbear** [gxr404/yuque-dl#17]
一篇文档是父级，会被识别成为文件夹目录，这种就无法下载下来，其实父级本身也是一篇文档

**Comment by gxr404** [comment]
能提供个语雀链接参考吗

**Comment by Greygbear** [comment]
https://www.yuque.com/meifangmia/zwcdgs/sxzg1xqft1gmm7g9

**Comment by gxr404** [comment]
> 一篇文档是父级，会被识别成为文件夹目录，这种就无法下载下来，其实父级本身也是一篇文档

已修复，更新至v1.0.44

**Comment by Greygbear** [comment]
已经更新到最新好像还是不行，还是上面那个链接。
https://www.yuque.com/meifangmia/zwcdgs/sxzg1xqft1gmm7g9
文章名称 ：三大视觉浏览模型
下载的只有这个名称的文件夹，但是这篇文档没有下载

**Comment by Greygbear** [comment]
通过 npm i -g yuque-dl 安装的版本还是1.0.41

**Comment by gxr404** [comment]
> 通过 npm i -g yuque-dl 安装的版本还是1.0.41

你是用淘宝的源吧 不知道淘宝的源什么时候同步

npm源已经是1.0.44了<https://www.npmjs.com/package/yuque-dl>
淘宝源还是1.0.41<https://npmmirror.com/package/yuque-dl>

**Comment by Greygbear** [comment]
太感谢了，已经成功了，谢谢！！！
