### ISSUE TITLE
下载知识库图片失败

### ISSUE THREAD

**Issue by uuuuuuuuuup** [gxr404/yuque-dl#18]
下载图片的知识库提示错误信息：
<img width="764" alt="image" src="https://github.com/gxr404/yuque-dl/assets/76818967/373c6a1c-41ac-45eb-a708-4557c09c9803">

**Comment by gxr404** [comment]
麻烦能提供下语雀链接吗

**Comment by gxr404** [comment]
可以更新v1.0.45试试
