### ISSUE TITLE
会把png图片下载成ico文件，导致md加载图片错误

### ISSUE THREAD

**Issue by Tangerinrs** [gxr404/yuque-dl#19]
知识库url：https://www.yuque.com/tianxiadamutou/zcfd4v
<img width="781" alt="Snipaste_2024-05-21_12-26-10" src="https://github.com/gxr404/yuque-dl/assets/117615605/c9a861bf-af77-4026-acd0-7432439931c7">
右键下载时确实都是png图片
<img width="1379" alt="Snipaste_2024-05-21_12-26-50" src="https://github.com/gxr404/yuque-dl/assets/117615605/1fd05ed7-e3fb-4956-a358-bbaf4329af0e">

**Comment by gxr404** [comment]
> 知识库url：[yuque.com/tianxiadamutou/zcfd4v](https://www.yuque.com/tianxiadamutou/zcfd4v) <img alt="Snipaste_2024-05-21_12-26-10" width="781" src="https://private-user-images.githubusercontent.com/117615605/332282396-c9a861bf-af77-4026-acd0-7432439931c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODgxMDAsIm5iZiI6MTcxNjI4NzgwMCwicGF0aCI6Ii8xMTc2MTU2MDUvMzMyMjgyMzk2LWM5YTg2MWJmLWFmNzctNDAyNi1hY2QwLTc0MzI0Mzk5MzFjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMDM2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTVjNjY3YmVjY2RiNTU4NTdjZjIwMzBmNmI1MmZkMjkyMWUyYWM4NTA1MGFlMTk5ZDYzYmRkYWY1OGQzZjExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.02gvVNoGB_hLDPfRQllA-ONOEcSo0QfLWKvhqzSIA4U"> 右键下载时确实都是png图片 <img alt="Snipaste_2024-05-21_12-26-50" width="1379" src="https://private-user-images.githubusercontent.com/117615605/332282557-1fd05ed7-e3fb-4956-a358-bbaf4329af0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODgxMDAsIm5iZiI6MTcxNjI4NzgwMCwicGF0aCI6Ii8xMTc2MTU2MDUvMzMyMjgyNTU3LTFmZDA1ZWQ3LWUzZmItNDk1Ni1hMzU4LWJiYWY0MzI5YWYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMDM2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWM1Y2IwNjQ0ZDc3YTAxMzFhNTc3NTkxYzdlYmI2NWE5OTZmYzlmYWQ3YTEzYzE4NTUwZmRkNDY2YmNiODJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pdPIGkLUzeoSAAu1I-SBIBsrqrqGeDZON0XDRcrajNs">

感谢反馈，已于v1.0.45 修复

**Comment by gxr404** [comment]
> Download [=======================================-] 97% | 207/212node:events:491 throw er; // Unhandled 'error' event ^
> 
> Error: ENAMETOOLONG: name too long, open 'path' Emitted 'error' event on WriteStream instance at: at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { errno: -63, code: 'ENAMETOOLONG', syscall: 'open', path: ------ } 下载路径过长无法继续下载

应该不是上面知识库url吧，我这没有类似的，应该修复了更新到v1.0.46试试
