### ISSUE TITLE
知识库下载图片错乱

### ISSUE THREAD

**Issue by kkoiuy** [gxr404/yuque-dl#20]
知识库库明明是有图片的但是下载后图片错乱导致![image.png](undefined)
<img width="632" alt="图片1" src="https://github.com/gxr404/yuque-dl/assets/170565016/88ba499d-d300-4de0-98aa-ce93127e4613">

然后整个文档的图片顺序就不对了
<img width="1272" alt="图片2" src="https://github.com/gxr404/yuque-dl/assets/170565016/53c00a6a-54ff-4eae-9671-1a0bbbdaeb39">

好像如果文档引用了同一个图片就会错乱

知识库 https://www.yuque.com/litanran/odz83t

**Comment by gxr404** [comment]
> 知识库库明明是有图片的但是下载后图片错乱导致![image.png](undefined) <img alt="图片1" width="632" src="https://private-user-images.githubusercontent.com/170565016/332922360-88ba499d-d300-4de0-98aa-ce93127e4613.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzYyOTEsIm5iZiI6MTcxNjQzNTk5MSwicGF0aCI6Ii8xNzA1NjUwMTYvMzMyOTIyMzYwLTg4YmE0OTlkLWQzMDAtNGRlMC05OGFhLWNlOTMxMjdlNDYxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzQ1NDUzN2VlMGYxOGNiOTVmZTY0ZmIxNDBkZjU1MTI3OWFkOTAxNTQ4N2U2OWQyYTQxMGI3NDRiODIzYTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vL0vuyNcwkdTJLmL7ZQedVductT6slTNYqjbpqbvIdE">
> 
> 然后整个文档的图片顺序就不对了 <img alt="图片2" width="1272" src="https://private-user-images.githubusercontent.com/170565016/332922391-53c00a6a-54ff-4eae-9671-1a0bbbdaeb39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzYyOTEsIm5iZiI6MTcxNjQzNTk5MSwicGF0aCI6Ii8xNzA1NjUwMTYvMzMyOTIyMzkxLTUzYzAwYTZhLTU0ZmYtNGVhZS05NjcxLTFhMGJiYmRhZWIzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMzQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGU5ZDdmMDI0M2M1ZTcxMWVhNjFmYWE4ZGFjZWI2MmQzMmViYjc3YTQwN2ExMTQwNGEwZDEwOWQ2MTM5ZGZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mkswIC89kolDcZf99dq4h-Gn6MRk_qTy4EkBNEhGS2Y">
> 
> 好像如果文档引用了同一个图片就会错乱
> 
> 知识库 [yuque.com/litanran/odz83t](https://www.yuque.com/litanran/odz83t)

确实是因为引用了相同图片导致的，v1.0.47已修复
