### ISSUE TITLE
文档中已失效图片链接下载导致文档顺序错乱

### ISSUE THREAD

**Issue by kkoiuy** [gxr404/yuque-dl#21]
这里原文档中没有这个图片链接了，但是下载的时候会被下载下来，导致文档顺序错乱
<img width="1489" alt="图片" src="https://github.com/gxr404/yuque-dl/assets/170565016/8e32af72-4f10-454c-815d-228235d2ab72">

知识库 https://www.yuque.com/tianxiadamutou/xqp4q6

**Comment by gxr404** [comment]
这个有点特殊 里面含有两张latex， 已修复 v1.0.48
