### ISSUE TITLE
文库中失效的本地图片引用地址

### ISSUE THREAD

**Issue by kkoiuy** [gxr404/yuque-dl#22]
<img width="1117" alt="图片" src="https://github.com/gxr404/yuque-dl/assets/170565016/d56c8ff3-ebfe-438b-866f-084c98e2bc0b">
这种文档中好像没有，或者是本地引用失效了，也被保存下来了，是否可以不保存呢。

知识库 https://www.yuque.com/tianxiadamutou/zcfd4v

**Comment by gxr404** [comment]
<img width="1285" alt="SCR-20240524-mfwq" src="https://github.com/gxr404/yuque-dl/assets/17134256/acdbab89-89c4-4cf2-b20f-8ff2487fd115">

<img width="1574" alt="SCR-20240524-mhma" src="https://github.com/gxr404/yuque-dl/assets/17134256/51e7ac6a-827b-49be-bcee-8d5e191387a1">

看了下 文档内是有的 而且还请求失败了，只是语雀没展示出来
不太好做处理，源就是错的，不好判断是正确的图片还是错误的

**Comment by kkoiuy** [comment]
好滴 辛苦您修复了
