### ISSUE TITLE
好像也是图片下载失败

### ISSUE THREAD

**Issue by SiMaLaoShi** [gxr404/yuque-dl#23]
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',

**Comment by gxr404** [comment]
能麻烦提供下 语雀的url 和 node版本吗

**Comment by gxr404** [comment]
好吧，必现的吗还是说其他知识库正常?
控制台完整的日志就上面那些吗?

**Comment by SiMaLaoShi** [comment]
> 好吧，必现的吗还是说其他知识库正常? 控制台完整的日志就上面那些吗?

不是必现的，上面的日志只哟这些

**Comment by SiMaLaoShi** [comment]
后面就是下载失败的日志了，估计跟下载数量有关，我下了库里面有几百条

**Comment by gxr404** [comment]
从上面的日志看不出来具体哪里的问题，只能尝试修复下 麻烦用v1.0.52 试试😂

**Comment by SiMaLaoShi** [comment]
> 从上面的日志看不出来具体哪里的问题，只能尝试修复下 麻烦用v1.0.52 试试😂

牛的我试试

**Comment by andwind1223** [comment]
Error: ENOENT: no such file or directory, open 'C:\Users\Lucas\download\一线互联网Java面试核心点(80万字)\面试必看\大厂真题\美团面试真题\String为什么要设计成不可变的.md\img\RTyDsLhvcIzYAhQ_\1717652766701-b3dbd756-c0d5-4a77-ae4f-ef89a94b901a-757964.png'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Lucas\\download\\一线互联网Java面试核心点(80万字)\\面试必看\\大厂真题\\美团面试真题\\String为什么要 设计成不可变的.md\\img\\RTyDsLhvcIzYAhQ_\\1717652766701-b3dbd756-c0d5-4a77-ae4f-ef89a94b901a-757964.png'
}

这好像也是下载不了图片。。

**Comment by gxr404** [comment]
> Error: ENOENT: no such file or directory, open 'C:\Users\Lucas\download\一线互联网Java面试核心点(80万字)\面试必看\大厂真题\美团面试真题\String为什么要设计成不可变的.md\img\RTyDsLhvcIzYAhQ_\1717652766701-b3dbd756-c0d5-4a77-ae4f-ef89a94b901a-757964.png' Emitted 'error' event on WriteStream instance at: at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'C:\Users\Lucas\download\一线互联网Java面试核心点(80万字)\面试必看\大厂真题\美团面试真题\String为什么要 设计成不可变的.md\img\RTyDsLhvcIzYAhQ_\1717652766701-b3dbd756-c0d5-4a77-ae4f-ef89a94b901a-757964.png' }
> 
> 这好像也是下载不了图片。。

方便提供下语雀的url吗

**Comment by andwind1223** [comment]
https://www.yuque.com/tulingzhouyu/db22bv/  密码 ilps

**Comment by gxr404** [comment]
> [yuque.com/tulingzhouyu/db22bv](https://www.yuque.com/tulingzhouyu/db22bv/) 密码 ilps

hi,请问是使用什么版本的呢? 我这边试了下,除去一些本身就404的文档其他都正常

 最新是`v1.0.56`

**Comment by andwind1223** [comment]
就是最新版本呀。。。然后我选则正常的也是报这个错。。

**Comment by andwind1223** [comment]
解决了，是我之前生成过。不好意思啊
