### ISSUE TITLE
找不到token 私有文档无法下载

### ISSUE THREAD

**Issue by tclyuuuu** [gxr404/yuque-dl#25]
貌似语雀要开超会才能看到token了，私有文档又需要token，请问有其他解决办法嘛。

**Comment by gxr404** [comment]
这里的token不是 语雀官方的[accessToken](https://www.yuque.com/yuque/developer/api#785a3731) , 而是你登录之后的cookie
[如何取token详细查看](https://github.com/gxr404/yuque-dl/blob/main/docs/GET_TOEKN.md)

**Comment by jxwuqingyan** [comment]
yuque最近是不是改了什么策略，原来可以的，今天重新登录用新的cookie值还是会报410。
![image](https://github.com/user-attachments/assets/87223893-e702-41d2-8c00-fa1b8effcb1c)

**Comment by gxr404** [comment]
> yuque最近是不是改了什么策略，原来可以的，今天重新登录用新的cookie值还是会报410。 ![image](https://private-user-images.githubusercontent.com/18183044/349399727-87223893-e702-41d2-8c00-fa1b8effcb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDA4ODcsIm5iZiI6MTcyMTIwMDU4NywicGF0aCI6Ii8xODE4MzA0NC8zNDkzOTk3MjctODcyMjM4OTMtZTcwMi00MWQyLThjMDAtZmExYjhlZmZjYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3MTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZWU2N2RmNDIyOGQ3ZGM5NTVjY2E4N2RiNzlmZDFmMDZjYTczOWRjNDIxOTA5ZDNmNGI0Y2FmMTA3ZDllOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BNHayVMmKLn_K3JbcbjvIyMwUTkcbaRYWBIFQBj7lmY)

我这边退出登录后重新拿token去下载私人知识库,  表现正常哦
有加-t参数cookie值`_yuque_session`吗？ 401看起来和404类似

**Comment by jxwuqingyan** [comment]
加了-t的，是我proxy的问题，已经好了，谢谢
