### ISSUE TITLE
可以下载附件吗

### ISSUE THREAD

**Issue by woshitieren** [gxr404/yuque-dl#26]
大神 请教一下可以下载附件吗

**Comment by gxr404** [comment]
更新到`1.0.55`，已支持

**Comment by gxr404** [comment]
> 1.0.56貌似下载附件都失败了 yuque-dl [ERROR]: ———— ✕ download article Error [yuque.com/xxxx/xxxxx/xxxxxxxxxxxxx](https://www.yuque.com/xxxx/xxxxx/xxxxxxxxxxxxx): 附件下载失败: Request failed with status code 400

我这边试了下是正常的，方便提供下 知识库的url吗

**Comment by veligerLi** [comment]
下载的附件PPT无法打开,都是固定的27kb

**Comment by gxr404** [comment]
> 下载的附件PPT无法打开,都是固定的27kb

方便提供下知识库的url吗

**Comment by veligerLi** [comment]
> > 下载的附件PPT无法打开,都是固定的27kb
> 
> 我这边模拟上传8M的PPT文件，下载正常。方便提供下知识库的url吗

https://www.yuque.com/leifengyang/live/design-pattern

**Comment by gxr404** [comment]
> > > 下载的附件PPT无法打开,都是固定的27kb
> > 
> > 
> > 我这边模拟上传8M的PPT文件，下载正常。方便提供下知识库的url吗
> 
> [yuque.com/leifengyang/live/design-pattern](https://www.yuque.com/leifengyang/live/design-pattern)

感谢反馈，请更新至`v1.0.59`, 下载附件需要有 token
其实如果退出语雀的账号再打开上面的url也是无法查看的，即使该知识库是完全公开的也需要登录

<img width="904" alt="SCR-20240715-rblk" src="https://github.com/user-attachments/assets/f8b50635-9937-4cb4-9e24-d6636cce6671">

更新至`v1.0.59` 执行下面命令即可正常下载附件

```bash
yuque-dl "https://www.yuque.com/leifengyang/live/design-pattern" -t "your token"
```

**Comment by veligerLi** [comment]
> > > > 下载的附件PPT无法打开,都是固定的27kb
> > > 
> > > 
> > > 我这边模拟上传8M的PPT文件，下载正常。方便提供下知识库的url吗
> > 
> > 
> > [yuque.com/leifengyang/live/design-pattern](https://www.yuque.com/leifengyang/live/design-pattern)
> 
> 感谢反馈，请更新至`v1.0.59`, 下载附件需要有 token 其实如果退出语雀的账号再打开上面的url也是无法查看的，即使该知识库是完全公开的也需要登录
> 
> <img alt="SCR-20240715-rblk" width="904" src="https://private-user-images.githubusercontent.com/17134256/348705907-f8b50635-9937-4cb4-9e24-d6636cce6671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTY5NDcsIm5iZiI6MTcyMzYxNjY0NywicGF0aCI6Ii8xNzEzNDI1Ni8zNDg3MDU5MDctZjhiNTA2MzUtOTkzNy00Y2I0LTllMjQtZDY2MzZjY2U2NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2MjQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNGE1MDQwOTY2NWJlMmEyM2NiNjc0NDgwMWExZDc2OTJlNmQwNGMxNzlhNGQxNmUyOTkzZWI2NjEyZmFiMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J2Kh87kIl4YyPSaQxT_Fc_rAi6LcShduXlTp_MeegFM">
> 更新至`v1.0.59` 执行下面命令即可正常下载附件
> 
> ```shell
> yuque-dl "https://www.yuque.com/leifengyang/live/design-pattern" -t "your token"
> ```

好的感谢

**Comment by veligerLi** [comment]
对了，下载的图片如果是有加了水印的，是不是可以去除。我看水印都是拼接在图片地址后面的

**Comment by gxr404** [comment]
> 对了，下载的图片如果是有加了水印的，是不是可以去除。我看水印都是拼接在图片地址后面的

能提供个知识库的链接吗 没看到有带水印的图片 😂

**Comment by veligerLi** [comment]
> > 对了，下载的图片如果是有加了水印的，是不是可以去除。我看水印都是拼接在图片地址后面的
> 
> 能提供个知识库的链接吗 没找到有带水印的图片 😂

https://www.yuque.com/veliger/fomkm3/og5afvkqdditasza

**Comment by gxr404** [comment]
更新至v1.0.63, 已默认去除水印
