### ISSUE TITLE
No found book id

### ISSUE THREAD

**Issue by Elex92** [gxr404/yuque-dl#27]
https://www.yuque.com/undefined-0a1zr/uqndsv/sbhh95u7zu2lx98g

yuque-dl "https://www.yuque.com/undefined-0a1zr/uqndsv/sbhh95u7zu2lx98g" -t "2Mgx9ksOvw8kdeQuPoqHDKCy"

**Comment by gxr404** [comment]
这个是 [密码登录的知识库](https://github.com/gxr404/yuque-dl#%E5%85%AC%E5%BC%80%E5%AF%86%E7%A0%81%E8%AE%BF%E9%97%AE%E7%9A%84%E7%9F%A5%E8%AF%86%E5%BA%93)

你这个token是`verified_books`或是`verified_docs`的值吗

**Comment by Elex92** [comment]
已解决，谢谢
