### ISSUE TITLE
一直提示这个 No found book id

### ISSUE THREAD

**Issue by Dalao521** [gxr404/yuque-dl#30]
good

**Comment by Zzzzzack2** [comment]
怎么解决

**Comment by Bany-Morningstar** [comment]
![Image](https://github.com/user-attachments/assets/472cadd6-742d-4a02-a4a1-3fe82e249ce5)

 https://www.yuque.com/tulingzhouyu/db22bv 

![Image](https://github.com/user-attachments/assets/bc638512-77c9-4e07-8122-9be001c916fa) 我哪里有问题吗

**Comment by gxr404** [comment]
> ![Image](https://github.com/user-attachments/assets/472cadd6-742d-4a02-a4a1-3fe82e249ce5)
> 
> [yuque.com/tulingzhouyu/db22bv](https://www.yuque.com/tulingzhouyu/db22bv)
> 
> ![Image](https://github.com/user-attachments/assets/bc638512-77c9-4e07-8122-9be001c916fa) 我哪里有问题吗

改用这个吧 这是[密码访问的知识库](https://github.com/gxr404/yuque-dl#%E5%85%AC%E5%BC%80%E5%AF%86%E7%A0%81%E8%AE%BF%E9%97%AE%E7%9A%84%E7%9F%A5%E8%AF%86%E5%BA%93)

```bash
yuque-dl "url" -k "verified_books" -t "verified_books的值"
```

**Comment by Bany-Morningstar** [comment]
我擦了，我的问题，我没分清文档里写的 1.已经登录语雀，访问需要密码的知识库 2.未登录语雀，访问需要密码的知识库。谢谢我给你点star
