### ISSUE TITLE
请输入密码访问当前知识库

### ISSUE THREAD

**Issue by swetich** [gxr404/yuque-dl#31]
利用 命令下载后，提示 yuque-dl [ERROR]: No found book id

**Comment by gxr404** [comment]
下载需要密码的知识库需 
```bash
yuque-dl "url" -k "verified_books" -t "verified_books的值"
```

详细[查看](https://github.com/gxr404/yuque-dl#%E5%85%AC%E5%BC%80%E5%AF%86%E7%A0%81%E8%AE%BF%E9%97%AE%E7%9A%84%E7%9F%A5%E8%AF%86%E5%BA%93)

**Comment by swetich** [comment]
verified_books 这个 book的id吗

**Comment by gxr404** [comment]
按这里获取[token的流程](https://github.com/gxr404/yuque-dl/blob/main/docs/GET_TOEKN.md) 找到verified_books这个cookie 复制里面的值
```bash
yuque-dl "知识库url" -k "verified_books" -t "verified_books 的cookie值"
```

**Comment by swetich** [comment]
关键是这个密码我不知道，我只是到他的链接，想下载他的内容

**Comment by gxr404** [comment]
....那做不到
这个工具做的是能访问得到的知识库下载到本地，做不到破解别人未公开的知识库，至少得知道密码😂

**Comment by swetich** [comment]
感谢作者的软件
