### ISSUE TITLE
不清楚有没有限制同时下载的数量或速率？

### ISSUE THREAD

**Issue by wade-Chan** [gxr404/yuque-dl#33]
就拍下猛了容易封，最好可以限制，不清楚有没有

**Comment by gxr404** [comment]
> 就拍下猛了容易封，最好可以限制，不清楚有没有

暂时没有，现在文档是一篇一篇的下，图片是并发20个请求的下
没有遇到过相关的问题，出现了可以再考虑做相关处理
一般来说公开的知识库封的话也只是封ip 不会影响用户账号
私有的的知识库才可能影响到对应token的用户
