### ISSUE TITLE
大佬，表格类导出时出现乱码

### ISSUE THREAD

**Issue by wangxin776** [gxr404/yuque-dl#35]
![image](https://github.com/user-attachments/assets/e27e13dd-a944-4f8e-9ec2-3931f9ead4ff)
语雀链接 https://www.yuque.com/fengqunketang/wev8hr 密码:igpp

**Comment by wangxin776** [comment]
用的是v1.0.58

**Comment by gxr404** [comment]
上面的已修复于v1.0.61，不过我看这个知识库的其他的文档 有部分表格还是会错乱，原因是 接口返回的的markdown数据就是错乱的... 这个不太好处理 后面我再想想有啥方法吧😂

**Comment by wangxin776** [comment]
好的，感谢大佬，辛苦了😁

**Comment by wangxin776** [comment]
大佬，这种通过嵌入本地文件的这种方式，我测试无法通过新增的“附件下载”功能下载对应的文件，这种可以下载吗
![image](https://github.com/user-attachments/assets/19ce29d8-9d25-4def-b1eb-b0ff510da19a)

**Comment by gxr404** [comment]
> 大佬，这种通过嵌入本地文件的这种方式，我测试无法通过新增的“附件下载”功能下载对应的文件，这种可以下载吗 ![image](https://private-user-images.githubusercontent.com/63399835/358192795-19ce29d8-9d25-4def-b1eb-b0ff510da19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjIwMjcsIm5iZiI6MTcyMzcyMTcyNywicGF0aCI6Ii82MzM5OTgzNS8zNTgxOTI3OTUtMTljZTI5ZDgtOWQyNS00ZGVmLWIxZWItYjBmZjUxMGRhMTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDExMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODFlNDZjMjI3ZjZlMDhlYWE1MWEwNzc1ZDg1NzgzYzkxOTk5ZjFjYjg4ZjRkNTEyNGY3NTQ5YzgzM2EyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-urKYIEvijYdMv4GK4lmlf9N0BrGyq5MgfP1q9SVxVk)

能提供下 有这种情况的知识库吗 我才好看能不能做 
只有会员才能上传 我没法模拟😂

**Comment by wangxin776** [comment]
> > 大佬，这种通过嵌入本地文件的这种方式，我测试无法通过新增的“附件下载”功能下载对应的文件，这种可以下载吗 ![image](https://private-user-images.githubusercontent.com/63399835/358192795-19ce29d8-9d25-4def-b1eb-b0ff510da19a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjIwMjcsIm5iZiI6MTcyMzcyMTcyNywicGF0aCI6Ii82MzM5OTgzNS8zNTgxOTI3OTUtMTljZTI5ZDgtOWQyNS00ZGVmLWIxZWItYjBmZjUxMGRhMTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDExMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmODFlNDZjMjI3ZjZlMDhlYWE1MWEwNzc1ZDg1NzgzYzkxOTk5ZjFjYjg4ZjRkNTEyNGY3NTQ5YzgzM2EyYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-urKYIEvijYdMv4GK4lmlf9N0BrGyq5MgfP1q9SVxVk)
> 
> 能提供下 有这种情况的知识库吗 我才好看能不能做 只有会员才能上传 我没法模拟😂

来了  https://www.yuque.com/laoge776/ahq486/msa2ntf95o1646xw  提供了pdf,word, 视频和音频作为测试

**Comment by gxr404** [comment]
v1.0.65 已支持视频， 音频的有点奇怪，能麻烦上面那个知识库 再添加一篇文档单独放音频吗 感谢

**Comment by wangxin776** [comment]
> v1.0.65 已支持视频， 音频的有点奇怪，能麻烦上面那个知识库 再添加一篇文档单独放音频吗 感谢

大佬太强了，我在知识库分别将excel、视频、音频、ppt、word、pdf单独存放在各自的文档中
![image](https://github.com/user-attachments/assets/243df009-af0b-4e14-8381-313c99d73430)

**Comment by gxr404** [comment]
v1.0.66 已支持音频下载了，只是语雀markdown的接口有缺陷，拿到的文档内容不含音频，只能统一下载后放到文档最后，没法准确定位到音频在文档中的位置

**Comment by wangxin776** [comment]
> 感谢提供示例 v1.0.66 已支持音频下载了，只是语雀markdown的接口有缺陷，接口拿到的文档内容不含音频 后续再看看有没有其他方案吧😂 暂时统一下载后放到文档最后，没法准确定位到音频在文档中的位置

大佬太强了，已经非常好了
