### ISSUE TITLE
使用yuque-dl执行下载命令没有反应

### ISSUE THREAD

**Issue by t192m** [gxr404/yuque-dl#36]
![image](https://github.com/user-attachments/assets/b816560f-2985-4cea-aca2-12dbadfebf2b)
如上图所示
https://www.yuque.com/yesir-sfo0q/nsut5g/it1p3gi5mfxh7ag6?singleDoc#
不需要token 求解

**Comment by t192m** [comment]
![image](https://github.com/user-attachments/assets/1ebdb380-f2a2-4ee4-83b3-40734da745da)
附上执行命令时当前版本 已更新至最新

**Comment by gxr404** [comment]
😂 查了好久这个问题。。。
应该是nodejs的问题 建议还是用nodejs的LTS版本，使用最新版有奇奇怪怪的问题，
 `22.4.1`这个版本可以而且mac版的 22.5.1也没问题， 这个问题在 win的22.5.0开始就有问题了 
大概是`mkdir('./a/术'，{recursive: true})`没创建成功也没报错 
换个中文都正常。。。`mkdir('./a/技'，{recursive: true})`创建成功且没报错
