### ISSUE TITLE
yuque-dl [ERROR]: No found book id

### ISSUE THREAD

**Issue by yellow-yes** [gxr404/yuque-dl#37]
执行报错：yuque-dl [ERROR]: No found book id
你们有遇到吗

**Comment by gxr404** [comment]
> 执行报错：yuque-dl [ERROR]: No found book id 你们有遇到吗

一般这种都是 私有知识库 需要带token 加`-t YOUR_TOKEN`

**Comment by wuwei258** [comment]
我今天也遇到这个问题了，下载样例里的文档也会报这个错误：
yuque-dl "https://www.yuque.com/yuque/thyzgp"
yuque-dl [ERROR]: No found book id

**Comment by gxr404** [comment]
> yuque-dl "[yuque.com/yuque/thyzgp](https://www.yuque.com/yuque/thyzgp)"

😂 应该是
`yuque-dl "https://www.yuque.com/yuque/thyzgp"`

**Comment by wuwei258** [comment]
<img width="640" alt="image" src="https://github.com/user-attachments/assets/0df87bb7-5473-457b-a338-1d514f3ecc1e">
如图

**Comment by gxr404** [comment]
> yuque-dl "https://www.yuque.com/yuque/thyzgp"

网络是否正常呢 跑一下看看结果`curl  "https://www.yuque.com/yuque/thyzgp"`

**Comment by wuwei258** [comment]
可以了，终端开了proxy。感谢大佬的工具~

**Comment by s3nail1** [comment]
我可以下载实例https://www.yuque.com/yuque/thyzgp 但是下载需要密码的不行，我添加了 _yuque_session

**Comment by s3nail1** [comment]
可以了，参数指定错了，之前指定的是 -k ，要指定 -t
