### ISSUE TITLE
非法文件名导致错误

### ISSUE THREAD

**Issue by SupernovaCooper** [gxr404/yuque-dl#4]
感谢作者，工具很好用，不过遇到了bug，导致任务没完成就没法继续了。
看起来应该是文件名中包含英文冒号导致创建目录失败（Windows中用的）。。。
- 下载 "aaaaaa" 的图片中...mdDownloadImg [ERROR]: mkdir error [Error: EINVAL: invalid argument, mkdir 'C:\Users\aaa\download\doc\img\356052:KMj1qXxjUIyM2Xa'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path: 'C:\\Users\\aaa\\download\\doc\\img\\35605452:KMjqXxj56UIyM2Xa'
}

node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\aaa\download\doc\img\356052:KMj1qXxjUIyM2Xa\1683-155246-29232.png'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\aaa\\download\\doc\\img\\356052:KMj1qXxjUIyM2Xa\1683-155246-29232.png'
}

Node.js v18.18.2

**Comment by gxr404** [comment]
感谢反馈。 已修复，请更新到最新版`1.0.20`。
由于没找到对应带有这种特殊符号的知识库，只能本地模拟测试。
麻烦有空也帮忙验证下，谢谢🙏

**Comment by SupernovaCooper** [comment]
新版很好用！谢谢大佬修复。
