### ISSUE TITLE
加粗的md语法解析优化

### ISSUE THREAD

**Issue by letsopen** [gxr404/yuque-dl#41]
** 加粗内容 **
以上语法解析后前后需要补空格才能展示加粗样式。
但是目前下载下来的内容没有补空格。

**Comment by gxr404** [comment]
**加粗内容**
** 沙发沙发 **
a ** 加粗内容 ** b
 a** 加粗内容 **b 
```md
**加粗内容**
** 沙发沙发 **
a ** 加粗内容 ** b
 a** 加粗内容 **b 
```
没太看明白 是指哪补空格 星号内补空格反而出错吧，星号外面前后加不加都没区别吧

**Comment by letsopen** [comment]
不好意思没说清楚，需要在外面补空格。

刚发现也有点奇怪，如果不补空格的话，md文档在语雀或者github上都不会显示加粗。
但是在有的markdown编辑器里面又不需要加空格。

**Comment by gxr404** [comment]
大概试了下 在语雀文档的编辑器， 下面内容逐个输入并没有当做是markdown内容
`**测试测试**`
在末尾最后敲个空格就识别为markdown内容，而这个空格也不会输入文档作为内容，**看接口返回的文档内容也不会带有空格**
同样在语雀的编辑器里面 输入 `#`的时候没识别为markdown，再敲一个空格 “#”没了 识别为markdown

我理解这个只是语雀编辑器做的特殊功能吧 
markdown规范里也没相关内容  😂
