### ISSUE TITLE
Enhancement: 增加日志输出到指定位置的功能

### ISSUE THREAD

**Issue by Wu-Jackie** [gxr404/yuque-dl#42]
如图，因本人下载量比较大，希望可以增加可选项：输出下载日志至指定位置（默认为和下载位置同一层级）以此方便后续查阅

**Comment by Wu-Jackie** [comment]
![screenshot](https://github.com/user-attachments/assets/b90a9232-098c-417c-9604-38b314008b64)

**Comment by gxr404** [comment]
在命令后面添加`> message.log` 即可，终端通用

```bash
yuque-dl "xxx" > message.log
```

**Comment by Wu-Jackie** [comment]
受益，感谢支持！
