### ISSUE TITLE
支持导出最近更新时间

### ISSUE THREAD

**Issue by bytes-code** [gxr404/yuque-dl#43]
大佬，想问一下，在语雀的每一篇文档当中都有最近更新时间，是否可以支持导出最近更新时间呢

**Comment by gxr404** [comment]
已支持，更新至`v1.0.67`

**Comment by bytes-code** [comment]
感谢大佬，更新版本后确实带有更新时间。不过更新后的版本好像带有一些html的标签，我找到之前的1.0.66版本的文档当中并没有带有这些标签。
![image](https://github.com/user-attachments/assets/d5bc8673-c4b1-4946-94e2-0689f2e0dd67)

**Comment by gxr404** [comment]
我刚刚也发现了好像是语雀接口的返回变了， 退回到哪个版本应该都一样，接口返回出来的数据改成带有html标签的

使用 `1.0.66`版本没有吗

```bash
npx yuque-dl@1.0.66 xxxurl
```

**Comment by bytes-code** [comment]
我8月22号使用1.0.66版本没有的

**Comment by gxr404** [comment]
> 我8月22号使用1.0.66版本没有的

嗯 我的意思是 如果**现在**用老版本还是带有html的 就代表是 最近语雀官方的接口 返回的结果变了
