### ISSUE TITLE
pptx 附件下载异常，带token

### ISSUE THREAD

**Issue by nonomal** [gxr404/yuque-dl#44]
yuque-dl [ERROR]: ———— ✕ 附件下载失败: ENOENT: no such file or directory, mkdir 'D:\Document\yuque\attachments\493380:rw6z8zrdikdvoe0g’

 ———— ✕ 图片下载失败(失败的以远程链接保存): Error Status Code: 403 https://cdn.nlark.co...

**Comment by gxr404** [comment]
> yuque-dl [ERROR]: ———— ✕ 附件下载失败: ENOENT: no such file or directory, mkdir 'D:\Document\yuque\attachments\493380:rw6z8zrdikdvoe0g’
> 
> ———— ✕ 图片下载失败(失败的以远程链接保存): Error Status Code: 403 [cdn.nlark.co](https://cdn.nlark.co)...

感谢反馈，根据上面的报错，大概修复了下，更新至`1.0.68`
我这边没有类似的知识库，能麻烦测下吗 或者方便提供下知识库吗

**Comment by WangSuxiao** [comment]
https://www.yuque.com/tulingzhouyu/db22bv?# 密码：vner

**Comment by gxr404** [comment]
> [yuque.com/tulingzhouyu/db22bv](https://www.yuque.com/tulingzhouyu/db22bv?#) 密码：vner
![SCR-20241011-ktcx](https://github.com/user-attachments/assets/1fab76b6-92bd-4b06-b80b-82e7a5992dbc)

具体是哪篇呢 我这边试了下 除了404和 `raw.githubus..`需要科学上网才能下载图片的 没其他错误了哦

**Comment by gxr404** [comment]
> [yuque.com/tulingzhouyu/db22bv](https://www.yuque.com/tulingzhouyu/db22bv?#) 密码：vner

![SCR-20241011-ktcx](https://github.com/user-attachments/assets/f897b36f-e8fe-46c9-ab0e-70ecf379f8bb)

试了下除了一些404和`https://raw.githubu`需要科学上网 没遇到上面问题

该知识库里面 总共三个ppt文件 ，打开都是异常 后面发现  [该附件就不是ppt文件](https://www.yuque.com/tulingzhouyu/db22bv/ep3vggcvyw79py1f)

**Comment by WangSuxiao** [comment]
感谢大佬，我换了Linux+Node.js v20.14.0成功下载
[cid:8d1f7f37-117a-4d89-9fa1-aaa3f7948c82]
windows+Node.js v22.9.0还是失败，感觉是我安装的问题，稍后重装有问题再向您反馈
________________________________
发件人: gxr404 ***@***.***>
发送时间: 2024年10月11日 12:59
收件人: gxr404/yuque-dl ***@***.***>
抄送: WangSuxiao ***@***.***>; Comment ***@***.***>
主题: Re: [gxr404/yuque-dl] pptx 附件下载异常，带token (Issue #44)


yuque.com/tulingzhouyu/db22bv<https://www.yuque.com/tulingzhouyu/db22bv?#> 密码：vner

SCR-20241011-ktcx.jpeg (view on web)<https://github.com/user-attachments/assets/f897b36f-e8fe-46c9-ab0e-70ecf379f8bb>

试了下除了一些404和https://raw.githubu需要科学上网 没遇到上面问题

该知识库里面 总共三个ppt文件 ，打开都是异常 后面发现 该附件就不是ppt文件<https://www.yuque.com/tulingzhouyu/db22bv/ep3vggcvyw79py1f>

―
