### ISSUE TITLE
表格中的文字没有保留换行

### ISSUE THREAD

**Issue by Greygbear** [gxr404/yuque-dl#46]
在文档中插入的普通表格，即使表格有合并单元格，也能很好导出不会乱码很赞
不过表格中的文字，换行会丢失
如果能支持换行保留的话就更好了

**Comment by gxr404** [comment]
大概试了下 确实在文档类型中插入表格 换行没了，估计不太好解决 没思路
语雀markdown接口返回的就是没换行的 😂

编辑文档时:
<img width="943" alt="SCR-20240914-nnva" src="https://github.com/user-attachments/assets/834345ca-dceb-4725-a006-06b9b6a39794">
接口返回的：
<img width="769" alt="SCR-20240914-noek" src="https://github.com/user-attachments/assets/a8f4cd2f-0357-45cd-8b5b-7191c3abe633">

**Comment by Greygbear** [comment]
我刚刚找到另一个工具好像可以，
https://github.com/vannvan/yuque-tools/tree/main

![image](https://github.com/user-attachments/assets/f5c8eb51-5532-4d0f-a8be-1e9673f3360d)

**Comment by Greygbear** [comment]
上面说的这个可以保留换行的工具。虽然可以保留换行，但是失败概率有点高，很多文档导出来内容是乱码。
要是咱们这个工具，也能支持换行就更好了。

**Comment by gxr404** [comment]
试了一下 yuque-tool 也是没导出`<br/>`

源文档:
<img width="1105" alt="SCR-20240914-pits" src="https://github.com/user-attachments/assets/d308e08d-d133-4097-a3dc-38bb5fff2500">

运行结果：
<img width="1020" alt="SCR-20240914-pigw" src="https://github.com/user-attachments/assets/ebbc4f5e-eba7-4800-b6ba-617c71b4a49e">

<img width="610" alt="SCR-20240914-piqi" src="https://github.com/user-attachments/assets/f981358f-26cb-4042-9a14-8cba49adb062">



或者 方便提供知识库url吗

**Comment by Greygbear** [comment]
https://www.yuque.com/g/shencibuxieci/xiam1a/tcart39cg1ezfwba/collaborator/join?token=L1oubefwjlztisrF&source=doc_collaborator&goto=%2Fshencibuxieci%2Fxiam1a%2Ftcart39cg1ezfwba%2Fedit# 邀请你共同编辑文档《文档1》

**Comment by Greygbear** [comment]
[文档1.md](https://github.com/user-attachments/files/17001814/1.md)
这是导出来的文件，有换行

**Comment by gxr404** [comment]
感谢反馈 上面那种 已经修复于`v1.0.70`，
<img width="1894" alt="111111111" src="https://github.com/user-attachments/assets/82accd72-d861-4576-9e97-aac912c798f1">

 可还是会存在 编辑时有换行导出是没有换行的情况(接口实际没返回) 这种两个工具都是导出不了换行的

**Comment by Greygbear** [comment]
感谢！假期快乐！
我晚点更新试试！
