### ISSUE TITLE
找不到文件或文件夹？

### ISSUE THREAD

**Issue by Dreamforher** [gxr404/yuque-dl#48]
<img width="363" alt="屏幕截图 2024-09-29 152058" src="https://github.com/user-attachments/assets/3e0dc234-2766-4dc8-89b3-d58cc71c823d">
无法下载

**Comment by gxr404** [comment]
```bash
yuque-dl "https://www.yuque.com/yuque/thyzgp"
```
无需尖括号包裹url

**Comment by Dreamforher** [comment]
<img width="368" alt="屏幕截图 2024-09-29 185405" src="https://github.com/user-attachments/assets/f369ae33-5582-4c21-b03c-b2ef21ebd9d4">
<img width="368" alt="屏幕截图 2024-09-29 185530" src="https://github.com/user-attachments/assets/ac975945-2a2a-41ba-b85b-999c47b41806">
<img width="382" alt="屏幕截图 2024-09-29 185610" src="https://github.com/user-attachments/assets/dcbe09d9-18e7-48f6-99fe-6da6f8ab6ca2">

**Comment by gxr404** [comment]
找不到命令就是环境变量里没找到yuque-dl

检查是否有执行全局安装

```bash
npm i -g yuque-dl 
```
