### ISSUE TITLE
下载没有反应，和输入-help效果一样

### ISSUE THREAD

**Issue by song782360037** [gxr404/yuque-dl#56]
## 基本信息

- 操作系统: Win11
- yuque-dl版本: 1.0.71
- Nodejs版本:22.4.1
- 方便的话提供语雀知识库的URL:https://www.yuque.com/hollis666/hkhtl7

> 提示: 检查是否开启vpn导致的异常
关闭VPN也是一样的

## 问题描述
![image](https://github.com/user-attachments/assets/1a8958b5-e434-4958-aabb-5142a6c1f378)

**Comment by gxr404** [comment]
这个是因为你的[token含有特殊符号](https://github.com/gxr404/yuque-dl#%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF) 改成

```bash
yuque-dl url -t="xxx" 
```

**Comment by song782360037** [comment]
> 这是因为你的[代币带有特殊符号](https://github.com/gxr404/yuque-dl#%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF)改成
> 
> ```shell
> yuque-dl url -t="xxx" 
> ```

已经解决感谢
