### ISSUE TITLE
感谢大佬。跪求出一个下载为PDF

### ISSUE THREAD

**Issue by odup** [gxr404/yuque-dl#57]
因为MD格式不能存放图片，只能引用。所以如果导出的不是自己的知识库，每次开启HTTP服务查看还是挺麻烦的。如果能导出到PDF，这样文字图片都齐全了。就会非常完美。

**Comment by gxr404** [comment]
之前有过这个想法 也尝试了下，小的知识库可能还好 
一些大的知识库 含图片一起 可能就能到达五六百M，转的话 时间久输出的pdf还大
后续有时间我再试试看吧 或者有啥好的解决方案也求推荐

**Comment by odup** [comment]
OKOK，还是感谢大佬。
