### ISSUE TITLE
以前删除的文档,还是会被拉下来

### ISSUE THREAD

**Issue by jxwuqingyan** [gxr404/yuque-dl#60]
## 基本信息

- 操作系统: rocky8.9
- yuque-dl版本: 1.0.73
- Nodejs版本: v20.16.0
- 方便的话提供语雀知识库的URL:

> 提示: 检查是否开启vpn导致的异常

## 问题描述
有一个以前删除的文档,还是会被拉下来
![image](https://github.com/user-attachments/assets/85362879-267c-4593-819f-d6e9309520fb)
![image](https://github.com/user-attachments/assets/cba0ee03-cc72-4dba-b7be-a7ed84836815)

**Comment by jxwuqingyan** [comment]
备注: 已经把整个download目录删除后全部重新下载测试的,不是重复运行yuque-dl ${url} -t ${token}下载的

**Comment by gxr404** [comment]
抱歉 没模拟出来😂
我模拟的步骤大概:
新建目录，目录下创建文档，执行yuque-dl后 检查目录完整
删除目录，且删除本地download目录，重新执行yuque-dl后 检查目录 删除的目录和目录下的文档并不存在,表现正常

> ps:把回收站的文档传递删除后 试试呢 (我的测试没有删除回收站的文档 表现也是正常)

**Comment by jxwuqingyan** [comment]
确实很神奇,回收站清了,然后账号token也退出重新登录过了,这个文件还是会被下载下来
