### ISSUE TITLE
请问如何下载表格呢？其他都正常下载，就表格不行

### ISSUE THREAD

**Issue by jxwuqingyan** [gxr404/yuque-dl#7]
node版本： v16.16.0  
os： centos7.9  
![image](https://github.com/gxr404/yuque-dl/assets/18183044/cb28d940-fa89-4054-9834-f48601343fd6)

**Comment by gxr404** [comment]
请更新到最新版1.0.27  `npm i -g yuque-dl`
已支持表格类型的文档的解析

<img width="1423" alt="截屏2024-02-20 02 57 06" src="https://github.com/gxr404/yuque-dl/assets/17134256/f7b99866-375f-4ec4-8a35-a51d08ae1e27">
<img width="509" alt="截屏2024-02-20 02 56 29" src="https://github.com/gxr404/yuque-dl/assets/17134256/86f035de-ebc9-43eb-b59c-1a5fcce9640f">

**Comment by jxwuqingyan** [comment]
经测试好像还是有问题
![image](https://github.com/gxr404/yuque-dl/assets/18183044/e2f7ac91-291f-48a3-a92f-33f3d3eeaaa6)

**Comment by jxwuqingyan** [comment]
sorry 这几个表是空的，是我的问题，给大佬点个赞，另外像这种待办清单要是能支持就完美了
![image](https://github.com/gxr404/yuque-dl/assets/18183044/0e50abd5-6670-485b-8d7d-8442541c96ff)  
![image](https://github.com/gxr404/yuque-dl/assets/18183044/ed150c9b-619b-42d5-b4fc-db66edb17a16)

**Comment by gxr404** [comment]
> sorry 上面的报错的表是空的，是我的问题，给大佬点个赞，另外像这种待办清单要是能支持就完美了 ![image](https://private-user-images.githubusercontent.com/18183044/306470806-0e50abd5-6670-485b-8d7d-8442541c96ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODY5NTksIm5iZiI6MTcwODQ4NjY1OSwicGF0aCI6Ii8xODE4MzA0NC8zMDY0NzA4MDYtMGU1MGFiZDUtNjY3MC00ODViLThkN2QtODQ0MjU0MWM5NmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NTIxMWI3ZDRjMTY3OGUwYzQ1ZmU5OTc5MzZhNTNmZDYzYTI2ZGQ0MTk4MDNhNjQwODI0MzM0ZGFhZmM0NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h1ymMUXKx_gZOeDCzFq_w1qGPVbuZLeWH1CY6HG6cj8) ![image](https://private-user-images.githubusercontent.com/18183044/306470550-ed150c9b-619b-42d5-b4fc-db66edb17a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODY5NTksIm5iZiI6MTcwODQ4NjY1OSwicGF0aCI6Ii8xODE4MzA0NC8zMDY0NzA1NTAtZWQxNTBjOWItNjE5Yi00MmQ1LWI0ZmMtZGI2NmVkYjE3YTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAzMzczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlOGUxOWI5ZTZmODNlZjVlNjhjZTY2ODAzNGZlNzQzOGY4OTRkMTM5MjE3MmU4MjkxNjcxYTM0NzRjMWY4NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0kub5VmqxTgV0AO82K4gT0TVotJ1bWBroyJrvhgtPC8)

空表的边界问题已经处理了，代办清单这种类型 后面有时间我研究下看看怎么实现，有点复杂😂

**Comment by jxwuqingyan** [comment]
好嘞 非常赞
