### ISSUE TITLE
指定下载目录，图片的地址还是在默认目录里

### ISSUE THREAD

**Issue by ZIUPAN** [gxr404/yuque-dl#8]

**Comment by ZIUPAN** [comment]
导致打开文件时读取不到图片

**Comment by gxr404** [comment]
请问具体的命令是咋样的 我测没发现有问题哦

```bash
# 指定下载目录为test
yuque-dl "https://www.yuque.com/yuque/thyzgp" -d test
```

![image](https://github.com/gxr404/yuque-dl/assets/17134256/2db4f979-bb06-498c-9634-a5249a981e19)

**Comment by lzhfdxhxm** [comment]
不使用相对路径，而是绝对路径的情况下，会在c盘那边生成图片信息，指定路径生成文件信息
![微信图片_20240508141024](https://github.com/gxr404/yuque-dl/assets/62536790/07fd7e01-5cc0-4157-92fd-32e0bef38573)
版本信息：
yuque-dl -v
yuque-dl/1.0.34 win32-x64 node-v20.12.2

**Comment by gxr404** [comment]
> 不使用相对路径，而是绝对路径的情况下，会在c盘那边生成图片信息，指定路径生成文件信息 ![微信图片_20240508141024](https://private-user-images.githubusercontent.com/62536790/328774067-07fd7e01-5cc0-4157-92fd-32e0bef38573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODQwOTgsIm5iZiI6MTcxNTE4Mzc5OCwicGF0aCI6Ii82MjUzNjc5MC8zMjg3NzQwNjctMDdmZDdlMDEtNWNjMC00MTU3LTkyZmQtMzJlMGJlZjM4NTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOWVjZGMzZGY4OTA1MzI1MzEyYzVmYmZiZjljYjE3NWZmOTI4MDhhZmM4NjFhODZiMzZiZTAwOWJiNTcyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CesA45xQ8j4kbzs-HTDmgUHZU16DWgxcrclpcm2EQvc) 版本信息： yuque-dl -v yuque-dl/1.0.34 win32-x64 node-v20.12.2

已修复，更新至1.0.40

**Comment by ZIUPAN** [comment]
> > 不使用相对路径，而是绝对路径的情况下，会在c盘那边生成图片信息，指定路径生成文件信息 ![微信图片_20240508141024](https://private-user-images.githubusercontent.com/62536790/328774067-07fd7e01-5cc0-4157-92fd-32e0bef38573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODQwOTgsIm5iZiI6MTcxNTE4Mzc5OCwicGF0aCI6Ii82MjUzNjc5MC8zMjg3NzQwNjctMDdmZDdlMDEtNWNjMC00MTU3LTkyZmQtMzJlMGJlZjM4NTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE1NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOWVjZGMzZGY4OTA1MzI1MzEyYzVmYmZiZjljYjE3NWZmOTI4MDhhZmM4NjFhODZiMzZiZTAwOWJiNTcyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CesA45xQ8j4kbzs-HTDmgUHZU16DWgxcrclpcm2EQvc) 版本信息： yuque-dl -v yuque-dl/1.0.34 win32-x64 node-v20.12.2
> 
> 已修复，更新至1.0.40

好耶
