### ISSUE TITLE
不能用了吗

### ISSUE THREAD

**Issue by 1024Distant** [gxr404/yuque-dl#9]
![1](https://github.com/gxr404/yuque-dl/assets/84264711/5b2833be-dff4-4ae6-9756-8f5493ff72f3)

**Comment by 1024Distant** [comment]
![2](https://github.com/gxr404/yuque-dl/assets/84264711/cfed0d69-6160-4325-a7dd-1ecb903e1141)
用的最新版本的，而且是你的示例地址，+我的token

**Comment by gxr404** [comment]
请问使用的nodejs版本多少

**Comment by 1024Distant** [comment]
我用的node是15.14.0，之后再试试18.4的行不行，应该是版本低了

**Comment by Jeddy** [comment]
> ![2](https://private-user-images.githubusercontent.com/84264711/311782094-cfed0d69-6160-4325-a7dd-1ecb903e1141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTYyMjgsIm5iZiI6MTcxMDI5NTkyOCwicGF0aCI6Ii84NDI2NDcxMS8zMTE3ODIwOTQtY2ZlZDBkNjktNjE2MC00MzI1LWE3ZGQtMWVjYjkwM2UxMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYTQyYTgxZjQ5OTMwM2U2MDgwZGIxZjkzNWM0N2NlZTA5ZDYxMjA0ZjBlNjE1OTVmMTQ0YzI4N2U1ZDZlZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CadomHRzoQZVSyN4HgrlCqJNKaxhsmZAebPFP4acxUI) 用的最新版本的，而且是你的示例地址，+我的token

node 18.19 一样，没有效果，也不报错。

**Comment by gxr404** [comment]
> > ![2](https://private-user-images.githubusercontent.com/84264711/311782094-cfed0d69-6160-4325-a7dd-1ecb903e1141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTYyMjgsIm5iZiI6MTcxMDI5NTkyOCwicGF0aCI6Ii84NDI2NDcxMS8zMTE3ODIwOTQtY2ZlZDBkNjktNjE2MC00MzI1LWE3ZGQtMWVjYjkwM2UxMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYTQyYTgxZjQ5OTMwM2U2MDgwZGIxZjkzNWM0N2NlZTA5ZDYxMjA0ZjBlNjE1OTVmMTQ0YzI4N2U1ZDZlZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CadomHRzoQZVSyN4HgrlCqJNKaxhsmZAebPFP4acxUI) 用的最新版本的，而且是你的示例地址，+我的token
> 
> node 18.19 一样，没有效果，也不报错。
<img width="641" alt="截屏2024-03-13 11 34 54" src="https://github.com/gxr404/yuque-dl/assets/17134256/75a77c83-3611-4d21-a32f-3aa35d79ef2c">

请问具体的操作系统和npm版本是什么？没有任何提示吗就卡在那吗  网络是否正常呢 😂

**Comment by ccsourcecode** [comment]
![Image 2xx](https://github.com/gxr404/yuque-dl/assets/67236396/5d35a862-8e8b-4d6e-9e6d-2e01833da90c)

![Image 2xx1](https://github.com/gxr404/yuque-dl/assets/67236396/d3df2dd7-d205-40b3-acb6-23871e8e5295)



yuque-dl [ERROR]: Unknown option `-5`


不成功呢

**Comment by gxr404** [comment]
> ![Image 2xx](https://private-user-images.githubusercontent.com/67236396/319264588-5d35a862-8e8b-4d6e-9e6d-2e01833da90c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTkzODYsIm5iZiI6MTcxMjE5OTA4NiwicGF0aCI6Ii82NzIzNjM5Ni8zMTkyNjQ1ODgtNWQzNWE4NjItOGU4Yi00ZDZlLTllNmQtMmUwMTgzM2RhOTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAyNTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTU4Zjc4ZTg3NmE5MGM0M2YyZTdjNzk4NTcxNjAxMjc4NDc1YTMyOTY0NzcwODhjODZkYTExNzcyNmRkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J5IVkgovuP7SDr13vDS2O9Sj6QqxkOZzYT3hSZ-RmCE)
> 
> ![Image 2xx1](https://private-user-images.githubusercontent.com/67236396/319265102-d3df2dd7-d205-40b3-acb6-23871e8e5295.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTkzODYsIm5iZiI6MTcxMjE5OTA4NiwicGF0aCI6Ii82NzIzNjM5Ni8zMTkyNjUxMDItZDNkZjJkZDctZDIwNS00MGIzLWFjYjYtMjM4NzFlOGU1Mjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAyNTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OGI2MDRjZGIyNDA2N2Q2MjJjNTg0ZDMwNzVlMzRmYWQ0OTdmZWM3ZjEzNmMyNGU3Y2E3ZTdkYjFmMGU0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g1kC6_XIsSqHsd2bT5voZeHAaStwBdTBZUqYDZfoR6U)
> 
> yuque-dl [ERROR]: Unknown option `-5`
> 
> 不成功呢

这个是因为输入的参数的值里有第一位为'-' ,  导致识别错误，如 k “-xxx” 改成 k="-xxx"

![SCR-1111120240404-jywg](https://github.com/gxr404/yuque-dl/assets/17134256/a7c6e97d-c8bd-4743-9e36-19b07fbfc1da)

**Comment by ccsourcecode** [comment]
Thanks for your reply.

還是不成功.

![Image 2xx](https://github.com/gxr404/yuque-dl/assets/67236396/f3993c07-4d27-476f-8e5c-e5f64afbbb30)
![Image 2xx1](https://github.com/gxr404/yuque-dl/assets/67236396/cd955198-28c7-42a3-89b0-b6347d3b1abd)

**Comment by gxr404** [comment]
> Thanks for your reply.
> 
> 還是不成功.
> 
> ![Image 2xx](https://private-user-images.githubusercontent.com/67236396/319430387-f3993c07-4d27-476f-8e5c-e5f64afbbb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDMyMjksIm5iZiI6MTcxMjIwMjkyOSwicGF0aCI6Ii82NzIzNjM5Ni8zMTk0MzAzODctZjM5OTNjMDctNGQyNy00NzZmLThlNWMtZTVmNjRhZmJiYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAzNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5ZGMzMmU0MTc2ZDA2Y2M3NjA1NjM2YmJkYzMyYzNhNGY0NTAzNDA5ZGIxODFjODk3NDA3NzY0ZjMyOGJkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ci8Pj76mI-_OV8EoXsS7wu9l0RQFtn3C3_CpHmIga1k) ![Image 2xx1](https://private-user-images.githubusercontent.com/67236396/319430394-cd955198-28c7-42a3-89b0-b6347d3b1abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDMyMjksIm5iZiI6MTcxMjIwMjkyOSwicGF0aCI6Ii82NzIzNjM5Ni8zMTk0MzAzOTQtY2Q5NTUxOTgtMjhjNy00MmEzLTg5YjAtYjYzNDdkM2IxYWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAzNTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YTdjMTIwMDUyY2Y5YTFjYjNlNjI0YzIzYzQ4NDhiNzZkOGY5Y2RhNDQ4YTY2ZTRhYzFhMmQzNDE0ZWFhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HfRqbd8o52dDurQznmFjdzW8b3DP7q0cY5qcJ_1BTwg)

你这个是企业私有服务吗看起来不像，如果不是 不需要带 -k ，token的值也是取`_yuque_session`,
[详细查看](https://github.com/gxr404/yuque-dl/blob/main/docs/GET_TOEKN.md)

**Comment by ccsourcecode** [comment]
應該不是 企業私有服務.

但是cookie 沒有 yuque_session 的 key, 只有 yuque_ctoken

![Image 2xx](https://github.com/gxr404/yuque-dl/assets/67236396/723a1668-841f-41f8-9f7b-8c6064d332dd)

**Comment by gxr404** [comment]
> 應該不是 企業私有服務.
> 
> 但是cookie 沒有 yuque_session 的 key, 只有 yuque_ctoken
> 
> ![Image 2xx](https://private-user-images.githubusercontent.com/67236396/319439030-723a1668-841f-41f8-9f7b-8c6064d332dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUyMzUsIm5iZiI6MTcxMjIwNDkzNSwicGF0aCI6Ii82NzIzNjM5Ni8zMTk0MzkwMzAtNzIzYTE2NjgtODQxZi00MWY4LTlmN2ItOGM2MDY0ZDMzMmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0Mjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNzllOGE5ZTQxN2E1YTlmZWE3YjlhMGQwYzNiZTI3MjBjOGUwMzA4NGEwNzk4MzYxY2NiZWQ4ZTNiZWE4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5jlpk4ntDqQaNq6yZYD-ezzl_-AdR1hWgR8ch_cV-oY)

哦哦 我发现了 这个是公开密码访问的知识库 我尝试了下是使用 verified_books或者是verified_docs 这个cookie
试试 `yuque-dl http://xxx -k “verified_books” -t "verified_books的值"`

**Comment by ccsourcecode** [comment]
成功了! 感謝! 可以的話 更新一下 ReadMe , 等其他人知道要用這個 key and token

![Image 2xx](https://github.com/gxr404/yuque-dl/assets/67236396/76cf568f-211e-482a-b2e9-4e9525919c20)

**Comment by andwind1223** [comment]
我也是公开密码访问的，可是没有verified_books这个cookie
